# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ""
author: The Bug Report Podcast
email: ben.everard@raspberrypi.org
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ben_everard
github_username:  benevpi
background: '/assets/bugreport.jpg'

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme_settings:
  title: Bug Report                 # Name of website
  avatar: assets/img/triangular.svg     # Path of avatar image, to be displayed in the theme's header
  gravatar: f98....6bfc                 # MD5 hash of your email address
  description: My blog posts            # Short description, primarily used by search engines
  header_text: 
  header_text_feature_image: assets/img/sample3.png
  footer_text: Copyright 2018

#this doesn't seem to be working
paginate: 5
paginate_path: "blog/page:num"
